config/routes.rb
Rails.application.routes.draw do
  resources :ingredients
  resources :recipes
  devise_for :users
  resources :authors
  root 'authors#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    validates :first_name, :presence => true
    belongs_to :user

    has_many :recipes, dependent: :nullify
    
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    
    belongs_to :author

    has_many :ingredients
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :authors
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  # GET /authors or /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1 or /authors/1.json
  def show
    @recipes = Recipe.all
  end

  # GET /authors/new
  def new
    #@author = Author.new
    @author = current_user.authors.build
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors or /authors.json
  def create
    #@author = Author.new(author_params)
    @author = current_user.authors.build(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: "Author was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @author = current_user.authors.find_by(id: params[:id])
    redirect_to root_path, notice: "No access" if @author.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:first_name, :last_name, :email_address, :user_id)
    end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: %i[ show edit update destroy ]

  # GET /ingredients or /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1 or /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
    @recipe = Recipe.find_by(id: params[:recipe_id])
  end

  # GET /ingredients/1/edit
  def edit
    @recipe = Recipe.find_by(id: params[:recipe_id])
  end

  # POST /ingredients or /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: "Ingredient was successfully created." }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1 or /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: "Ingredient was successfully updated." }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1 or /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to recipe_path(@ingredient.recipe_id), notice: "Ingredient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ingredient_params
      params.require(:ingredient).permit(:ingredient_name, :amount, :unit, :recipe_id)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show edit update destroy ]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @author = Author.find_by(id: @recipe.author_id)
    @ingredients = Ingredient.all
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @author = Author.find_by(id: params[:author_id])
  end

  # GET /recipes/1/edit
  def edit
    @author = Author.find_by(id: params[:author_id])
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: "Recipe was successfully created." }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: "Recipe was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to author_path(@recipe.author_id), notice: "Recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:recipe_name, :difficulty, :author, :comment, :author_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name, class: 'form-label' %>
    <%= form.text_field :first_name, class: 'form-control' %>
  </div>
  <br>
  <div class="field">
    <%= form.label :last_name, class: 'form-label' %>
    <%= form.text_field :last_name, class: 'form-control' %>
  </div>
  <br>
  <div class="field">
    <%= form.label :email_address, class: 'form-label' %>
    <%= form.email_field :email_address, class: 'form-control' %>
  </div>

  
  <%= form.number_field :user_id, id: :author_user_id, class: 'form-control', value: current_user.id, type: :hidden %>

  <br>
  <div class="actions">
    <%= form.submit class: 'btn btn-outline-dark' %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>
<br>
<%= link_to 'Show', @author, class: 'btn btn-outline-dark' %> |
<%= link_to 'Back', authors_path, class: 'btn btn-outline-dark' %>

app/views/authors/index.html.erb
<h1>Authors</h1>

<table class='table'>
  <thead class="table-light">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <% if author.user == current_user %>
        <tr>
          <td><%= author.first_name %> <%= author.last_name %></td>
          <td><%= author.email_address %></td>
          <td><%= link_to 'Show', author, class: 'btn btn-outline-dark' %></td>
          <td><%= link_to 'Edit', edit_author_path(author), class: 'btn btn-outline-dark' %></td>
          <td><%= link_to 'Delete', author, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-dark' %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path, class: 'btn btn-outline-dark' %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>
<br>
<%= link_to 'Back', authors_path, class: 'btn btn-outline-dark' %>

app/views/authors/show.html.erb
<div class="card" style="width: 24rem;">
  <div class="card-body">
    <u><h5 class="card-title">Author info</h5></u>
    <p>
      <strong>Name:</strong>
      <%= @author.first_name %> <%= @author.last_name %>
    </p>

    <p>
      <strong>Email address:</strong>
      <%= @author.email_address %>
    </p>
    <%= link_to 'Edit', edit_author_path(@author), class: 'btn btn-outline-dark' %> |
    <%= link_to 'Back', authors_path, class: 'btn btn-outline-dark' %>
  </div>
</div>

<%= render 'recipes/recipe_list' %>

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient) do |form| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
        <% ingredient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ingredient_name, class: 'form-label' %>
    <%= form.text_field :ingredient_name, class: 'form-control' %>
  </div>
  <br>
  <div class="field">
    <%= form.label :amount, class: 'form-label' %>
    <%= form.number_field :amount, class: 'form-control', step: 0.1 %>
  </div>
  <br>
  <div class="field">
    <%= form.label :unit, class: 'form-label' %>
    <%= form.select :unit, options_for_select([["Select One", ""], "Grams", "Milliliters", "Pieces"]), {}, { class: "form form-group form-control" } %>
  </div>

  <%= form.text_field :recipe_id, class: 'form-control', value: params[:recipe_id], type: :hidden %>

  <br>
  <div class="actions">
    <%= form.submit class: 'btn btn-outline-dark' %>
  </div>
<% end %>

app/views/ingredients/_ingredient_list.html.erb
<br>

<h1>Ingredients</h1>

<table class='table'>
  <thead class="table-light">
    <tr>
      <th>Ingredient name</th>
      <th>Amount</th>
      <th>Unit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <% if ingredient.recipe_id == @recipe.id %>
        <tr>
          <td><%= ingredient.ingredient_name %></td>
          <td><%= ingredient.amount %></td>
          <td><%= ingredient.unit %></td>
          <td><%= link_to 'Show', ingredient, class: 'btn btn-outline-dark' %></td>
          <td><%= link_to 'Edit', edit_ingredient_path(ingredient, recipe_id: ingredient.recipe_id), class: 'btn btn-outline-dark' %></td>
          <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-dark' %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add ingredient', new_ingredient_path(recipe_id: @recipe.id), class: 'btn btn-outline-dark' %>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>
<br>
<%= link_to 'Show', @ingredient, class: 'btn btn-outline-dark' %> |
<%= link_to 'Back', recipe_path(@ingredient.recipe_id), class: 'btn btn-outline-dark' %>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ingredients</h1>

<table class='table'>
  <thead class="table-light">
    <tr>
      <th>Ingredient name</th>
      <th>Amount</th>
      <th>Unit</th>
      <th>ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.ingredient_name %></td>
        <td><%= ingredient.amount %></td>
        <td><%= ingredient.unit %></td>
        <td><%= ingredient.id %></td>
        <td><%= link_to 'Show', ingredient %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>
<br>
<%= link_to 'Back', recipe_path(params[:recipe_id]), class: 'btn btn-outline-dark' %>

app/views/ingredients/show.html.erb
<div class="card" style="width: 24rem;">
  <div class="card-body">
    <u><h5 class="card-title">Ingredient info</h5></u>
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Ingredient name:</strong>
      <%= @ingredient.ingredient_name %>
    </p>

    <p>
      <strong>Amount:</strong>
      <%= @ingredient.amount %>
    </p>

    <p>
      <strong>Unit:</strong>
      <%= @ingredient.unit %>
    </p>

    <%= link_to 'Edit', edit_ingredient_path(@ingredient, recipe_id: @ingredient.recipe_id), class: 'btn btn-outline-dark' %> |
    <%= link_to 'Back', recipe_path(@ingredient.recipe_id), class: 'btn btn-outline-dark' %>
  </div>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'ReciPlease', root_path, class: 'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="btn-group dropstart">
        <button type="button" class="btn btn-outline-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
          Menu
        </button>
        <ul class="dropdown-menu">
          <% if user_signed_in? %>
            <li><u><%= link_to current_user.email, edit_user_registration_path, class: 'dropdown-item' %></u></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %></li>
            <li><%= link_to 'Edit user profile', edit_user_registration_path, class: 'dropdown-item' %></li>
          <% else %>
            <li><%= link_to 'Sign in', new_user_session_path, class: 'dropdown-item' %></li>
            <li><%= link_to 'Create user profile', new_user_registration_path, class: 'dropdown-item' %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <title>Hello, world!</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header'%>
    <div class='container'>
      <br>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :recipe_name, class: 'form-label' %>
    <%= form.text_field :recipe_name, class: 'form-control' %>
  </div>
  <br>
  <div class="field">
    <%= form.label :comments, class: 'form-label' %>
    <%= form.text_area :comment, class: 'form-control' %>
  </div>
  <br>
  <%= form.label :difficulty, class: 'form-label' %>
  <%= form.select :difficulty, options_for_select([["Select One", ""], "Easy", "Intermediate", "Pro", "Chef"]), {}, { class: "form form-group form-control" } %>

  <br>

  <div class="field">
    <%= form.label 'Author name:', class: 'form-label' %>
    <%= @author.first_name %> <%= @author.last_name %>
  </div>

  
  <%= form.text_field :author_id, class: 'form-control', value: params[:author_id], type: :hidden %>

  
  <br>
  <div class="actions">
    <%= form.submit class: 'btn btn-outline-dark' %>
  </div>
<% end %>

app/views/recipes/_recipe_list.html.erb
<br>
<h1><%= @author.first_name %>'s Recipes</h1>

<table class='table'>
  <thead class="table-light">
    <tr>
      <th>Recipe name</th>
      <th>Difficulty</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <% if recipe.author_id == @author.id %>
        <tr>
          <td><%= recipe.recipe_name %></td>
          <td><%= recipe.difficulty %></td>
          <td><%= recipe.comment %></td>
          <td><%= link_to 'Show', recipe, class: 'btn btn-outline-dark' %></td>
          <td><%= link_to 'Edit', edit_recipe_path(recipe, author_id: recipe.author_id), class: 'btn btn-outline-dark' %></td>
          <td><%= link_to 'Delete', recipe, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-dark' %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add recipe', new_recipe_path(author_id: @author.id), class: 'btn btn-outline-dark' %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>
<br>
<%= link_to 'Show', @recipe, class: 'btn btn-outline-dark' %> |
<%= link_to 'Back', author_path(@recipe.author_id), class: 'btn btn-outline-dark' %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<table class='table'>
  <thead class="table-light">
    <tr>
      <th>Recipe name</th>
      <th>Difficulty</th>
      <th>Author</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.recipe_name %></td>
        <td><%= recipe.difficulty %></td>
        <td><%= recipe.author_id %></td>
        <td><%= recipe.comment %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>
<br>
<%= link_to 'Back', author_path(params[:author_id]), class: 'btn btn-outline-dark' %>

app/views/recipes/show.html.erb
<div class="card" style="width: 24rem;">
  <div class="card-body">
    <u><h5 class="card-title">Recipe info</h5></u>
    <p>
      <strong>Recipe name:</strong>
      <%= @recipe.recipe_name %>
    </p>

    <p>
      <strong>Difficulty:</strong>
      <%= @recipe.difficulty %>
    </p>

    <p>
      <strong>Author:</strong>
      <%= @author.first_name %> <%= @author.last_name %>
    </p>

    <p>
      <strong>Comments:</strong>
      <%= @recipe.comment %>
    </p>

    <%= link_to 'Edit', edit_recipe_path(@recipe, author_id: @recipe.author_id), class: 'btn btn-outline-dark' %> |
    <%= link_to 'Back', author_path(@recipe.author_id), class: 'btn btn-outline-dark' %>
  </div>
</div>

<%= render 'ingredients/ingredient_list' %>